### ISSUE TITLE
22時半の会議について

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#1]
以下のことを考えてきてください。
もしくは、こちらにメモしてもいい

1. どこまでが完成？
2. 自分がやりたいことについて。

**Comment by OIC-Shinchaemin** [comment]
こちらに返事形式に書いてください

**Comment by darkstars-hub** [comment]
1.ラチェット＆クランクの１ステージと雑魚敵、普通の敵、ボス。ガラメカの５種類以上、キャラのほぼ再現　完成

**Comment by OIC-Shinchaemin** [comment]
大体１２時までにはやるつもり

**Comment by darkstars-hub** [comment]
2.敵キャラ（ボス含む）の制御、ガラメカの挙動です

**Comment by KoreanGinseng** [comment]
1.川村君とほぼ同じで、追加でステージギミックはステージ１のノヴァリス？のギミック再現
2.エディタ関連、サンプル作成

**Comment by OIC-Shinchaemin** [comment]
> 1.川村君とほぼ同じで、追加でステージギミックはステージ１のノヴァリス？のギミック再現
> 2.エディタ関連、サンプル作成

あれ？井上さんも川村と同じ所も作りたいってこと？

**Comment by OIC-Shinchaemin** [comment]
MOFLiblary使う？

使うとしたら、３D素材はどうするか？

**Comment by OIC-Shinchaemin** [comment]
時間があれば、Gitの管理方法についても相談
ー　ラベルはどうする？
ー　プルリクエストは何人がどうする？

**Comment by darkstars-hub** [comment]
×ステージと
〇ステージの　です
ナビゲーションデータがあるならステージも少しいいなと思っています

**Comment by darkstars-hub** [comment]
学内ライブラリを使わないなら
openglがいいと思いますモデルデータはassimpで読み込めばできるはずです

**Comment by KoreanGinseng** [comment]
> あれ？井上さんも川村と同じ所も作りたいってこと？

最終的な目的は一緒で、このプロジェクトの完成とするならステージギミックも必要かなと思ったので。
僕のエディタでの完成目標はオブジェクトの配置、設定、ギミックの配置、設定ができるようにする。ですね。

**Comment by darkstars-hub** [comment]
素材は　https://assetstore.unity.com/packages/3d/animations/animation-for-platform-game-182928
              https://sketchfab.com/3d-models/forest-golem-03-686fe8f75b094efd9bdb8abe0dc7f194 
がいいと思います

**Comment by KoreanGinseng** [comment]
gl使うなら4.5以上のバージョンがいいね

**Comment by darkstars-hub** [comment]
実装の優先順位なんですが、
考えているものとしては
自キャラ制御
敵キャラ制御
武器使用
ステージ（ギミック含む）
とかでいいと思います

**Comment by KoreanGinseng** [comment]
清家くんが3人のプロジェクトの中からいいとことって整理して、清家氏の書き方で作る。
外部から呼ぶ場合、インスタンス化してInitialize()、Update()、Render()、Release()呼ぶだけで動くものを作る。

**Comment by KoreanGinseng** [comment]
井上はステージのクラスもInitialize()、Update()、Render()、Release()すればいいだけの形にする。

**Comment by darkstars-hub** [comment]
川村のやること
敵キャラ
ゲームシステム（外部ファイルへの書き込みUIの表示とUIが参照するデータの管理）　今はシーンの遷移を考慮しない
二人のコードの合体

**Comment by OIC-Shinchaemin** [comment]
申：上の三つをタスクにする

**Comment by OIC-Shinchaemin** [comment]
先にMOFLibで。
OpenGL、DirectXもいずれか作成

**Comment by OIC-Shinchaemin** [comment]
川村：WIKIに全体的な構成を書く

**Comment by darkstars-hub** [comment]
二人のコードの合体は土曜日には開始

**Comment by darkstars-hub** [comment]
着手順番は
WIKIに全体的な構成を書く
ゲームシステム
敵キャラ
二人のコードの合体

でやっていきます

**Comment by OIC-Shinchaemin** [comment]
VS2019 , C++17

MOFLib Folder パス設定
→ 明日午前中に教える（申）

**Comment by OIC-Shinchaemin** [comment]
> 着手順番は
> WIKIに全体的な構成を書く
> ゲームシステム
> 敵キャラ
> 二人のコードの合体
> 
> でやっていきます

タスク作成しました。（川村から）
WIKI - https://ex-oic.cloudmine.jp/issues/22
ゲームシステム - https://ex-oic.cloudmine.jp/issues/23
敵キャラ - https://ex-oic.cloudmine.jp/issues/24
マージ - https://ex-oic.cloudmine.jp/issues/25

**Comment by OIC-Shinchaemin** [comment]
> 3人

タスク作成しました。
https://ex-oic.cloudmine.jp/issues/26

**Comment by OIC-Shinchaemin** [comment]
> 井上はステージのクラスもInitialize()、Update()、Render()、Release()すればいいだけの形にする。

タスク作成しました。
https://ex-oic.cloudmine.jp/issues/27
https://ex-oic.cloudmine.jp/issues/28
