### ISSUE TITLE
【Unity】ステージ１のフィードバック

### ISSUE THREAD

**Issue by nagishimizu** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#103]
実際にプレイしてみた感想をコメントに書き込んでください。

**Comment by darkstars-hub** [comment]
せっかくなので辛口でいきます
・まずゲーム開始の時に攻撃ボタンを押してと書いているけど、攻撃ボタンがどれか初めはわからなかった

・中間のステージに中ボスらしきカエルがいるけど、その前に攻撃機能を試している間に死んでいた

・ゲームによる部分だと思うけども、操作した感じがマリオとかに比べると横の移動量が大きく、ジャンプ開始が少し遅い。
また落下速度が速いと思う。

・次に進むためのオブジェクトに当たるとすぐに画面が切り替わるから、十字キーの上などのキーを押したときに切り替わるようにしてもらえるとわかりやすいと思う。

・死んだときにBGMがまだ実装されていないから、本来なら音が鳴っているであろう時間の分だけ画面が止まっていると感じた。

・１つ１つアクションごとに効果音が欲しい

・プレイヤーの攻撃方向が固定だからボスの攻撃を迎撃するのが難しい。せっかく打ち消し合わせることができるなら向きを
変えたりする機能が欲しかった。


短期間で１つのゲームのステージとして形になっているのはとてもすごいと思う
書いた内容ではBGMと効果音がしっかりついていれば、よりそれらしいものになると思う
