### ISSUE TITLE
GitとRedmine作業の流れ

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#11]
後で書いておきます！

**Comment by OIC-Shinchaemin** [comment]
WIKI作成予定

**Comment by OIC-Shinchaemin** [comment]
https://ex-oic.cloudmine.jp/issues/35
タスク作成しました。

**Comment by darkstars-hub** [comment]
Discordより転載

GitのIssueを確認　→　Redmineでチケット作成　→　チケット名に合わせてブランチ作成　→　作業　→　Push（リモートには同じブランチ名のブランチ作成）→　プールリクエスト（リモート作業ブランチからMofLibへ）
例）チケット作成（３３）→　MofLibブランチからEX33_XXXブランチ作成　→　作業　→　Push（RemoteのEX33_XXXブランチに）→　PullRequest（EX33_XXXブランチ→MofLibへ）
