### ISSUE TITLE
フォルダ構成について

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#2]

**Comment by OIC-Shinchaemin** [comment]
とりあえず、プロジェクトフォルダとエディターフォルダは分けてある。

追加フォルダ構成が必要なところは？

ex ) 
・エディターのSample フォルダ？、リソースフォルダはクライアントとエディター別？
・井上さんと川村さんが同じところをまた作ることになる場合、どうしようか？
・Unityは別リポジトリがいいかな？（クローンする容量を考えると・・・）

**Comment by KoreanGinseng** [comment]
エディタのデータ読み込むクラスのファイルの配置とプロジェクトからのフィルタの階層とかどうすればいいですか？
とりあえずRachetのとこに入れてます。

**Comment by darkstars-hub** [comment]
ステージエディタの出力ファイルは　Resourceディレクトリにmapやstageの名前でディレクトリを作ってその中に入れればいいと思います

**Comment by darkstars-hub** [comment]
Stage.h Stage.cpp は　Stageに紐づくファイルが少ないならそのまま入れてもいいと思います。
ステージのギミックなどが出てくるなら Stageディレクトリ作ればいいと思います

**Comment by darkstars-hub** [comment]
05/20時点での構成で進める
修正することはないと思う

**Comment by darkstars-hub** [comment]
- [ ]
