### ISSUE TITLE
作業の定義_実装する内容の洗い出し_09_08

### ISSUE THREAD

**Issue by b8105** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#202]
再開するので
以降実装する内容を洗い出す

**Comment by b8105** [comment]
デバッグモードはキーで切り替えられるようにする

**Comment by b8105** [comment]
タイトルロゴをフェードインされるようにする
シェーダでやってもいいかも

**Comment by b8105** [comment]
ゲームシーン入り
プレイヤーの追従カメラが有効になったら
タスクをスライドインさせて光らせる

**Comment by b8105** [comment]
音源を探す

**Comment by b8105** [comment]
文字がジャンプする

**Comment by darkstars-hub** [comment]
ソース整理してからテキストクラスの
コレ
https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/issues/203

**Comment by darkstars-hub** [comment]
ゲームスタート　→　イベント　→　エルフと話す　→　イベント　→　カメラ回転（かかしがみえるように）　⇒　行ってかかしを倒す　⇒　画面の左？にイベントメッセージを出す（エルフと話してみたな？）⇒　エルフに戻る　⇒　クエスト完了＆次のイベント　⇒　繰り返し３回

エフェクトはかかしが攻撃されるとき
課題のやつ適当に１個

**Comment by darkstars-hub** [comment]
エレベーター乗る

**Comment by darkstars-hub** [comment]
チュートリアルは2種類

**Comment by darkstars-hub** [comment]
中央広部にむかえ！　メッセージと
HPの表示は
チュートリアル中はいらない

**Comment by darkstars-hub** [comment]
船の修理に敵の骨が　必要
倒した敵（骨）の集めて

**Comment by darkstars-hub** [comment]
エレベーターを降りたら
敵を見渡すカメラのイベントを作る
それからプレイヤーの操作ができる

**Comment by darkstars-hub** [comment]
・描画レイヤの都合で
！マークの後ろにステージオブジェクトがあると
青いのが透けてしまう

・カメラを正面（プレイヤーの向いている方向）に切り替えるときに不自然さが出ている

**Comment by darkstars-hub** [comment]
王様の方を向く

**Comment by darkstars-hub** [comment]
エレベーター降下中の
カメラを滑らかに

**Comment by darkstars-hub** [comment]
スムーズに
一番最初に倒さないといけない敵を見て

降りたら自動でジャンプ

0.2くらい
止まって
進む先の敵を見て
自分のカメラに切り替わる
切り替わる

**Comment by darkstars-hub** [comment]
Kingクラスでメモリリークが見つかった

**Comment by darkstars-hub** [comment]
解決

テストコードが残ってた

**Comment by darkstars-hub** [comment]
カメラ
カメラが埋まる
カメラがカクつく
カメラ切り替えの見せ方が滑らかでない、


敵に攻撃したとき
近接ならゲームにポーズをかけるヒットストップ
近接なら弾丸がはじけるようなエフェクト

操作感向きたいところに向けるように
攻撃を当てやすく
ラチェットに寄せるならのラチェットの操作感を大事に


キーが分かりにくい
チュートリアル中でもいいから表示させてもいいかも
よく使うキーは集めておく
テキストを進めるのはSPACEでいいかも
