### ISSUE TITLE
修正してほしいところ

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#203]
追加していきますので終わったのはスタンプ入れてください。

**Comment by OIC-Shinchaemin** [comment]
タイトル以外ではESCキーで終了じゃなく、メニューを表示するように

**Comment by OIC-Shinchaemin** [comment]
キーの変更
B　：ガード
N　：攻撃（今のまま）
M　：ジャンプ

**Comment by OIC-Shinchaemin** [comment]
メニューの構成を変えましょう

ゲームにもどる
タイトールにもどる
ゲーム終了

**Comment by OIC-Shinchaemin** [comment]
メニューが出たら、最初は「ゲームにもどる」にフォーカスするように

**Comment by OIC-Shinchaemin** [comment]
敵が出るとき、最初だけプレイヤーに何かのエフェクトをつけましょう
（スパイダーマンのセンスみたいな）

**Comment by OIC-Shinchaemin** [comment]
攻撃されたとき、何かのエフェクトを入れましょう。

**Comment by OIC-Shinchaemin** [comment]
進行方向によってのカメラ回転

**Comment by b8105** [comment]
オーディオ実装

**Comment by darkstars-hub** [comment]
シーン遷移の時にエフェクトを入れる
まず、タイトルからゲーム部分に入るときにフェードインする

**Comment by darkstars-hub** [comment]
テキストメッセージ機能を入れる
メッセージ表示中はゲームをポーズ中にする

**Comment by darkstars-hub** [comment]
昇降機のギミックを始めは見えないようにする。
それと
崖のところに見えない壁を用意する

**Comment by darkstars-hub** [comment]
カメラのアングル調整（’値変える）

**Comment by darkstars-hub** [comment]
初期位置の後ろに　トレーニング用にカカシを用意する
この敵は動かない

**Comment by darkstars-hub** [comment]
チュートリアルフラグを用意する
攻撃できないとかにして
フラグによってプレイヤーのアクションを制限する

**Comment by darkstars-hub** [comment]
ゲーム中のメニューの位置調整

**Comment by darkstars-hub** [comment]
https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/issues/203#issuecomment-916921409

https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/issues/203#issuecomment-916926922

https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/issues/203#issuecomment-916924730

https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/issues/203#issuecomment-915775729

**Comment by darkstars-hub** [comment]
かかしは動かない

**Comment by darkstars-hub** [comment]
マップほしい

**Comment by darkstars-hub** [comment]
下にも家いくつか置く

**Comment by darkstars-hub** [comment]
ちょっとくらい　ライト２こにてもいいかも

**Comment by darkstars-hub** [comment]
王様に近づいたらテキストを表示

**Comment by darkstars-hub** [comment]
テキスト表示中はキャラクタの入力を受け付けない

**Comment by darkstars-hub** [comment]
案山子三体
詳しくはまた明日

**Comment by darkstars-hub** [comment]
クエスト受注ー＞実行ー＞達成イベントの処理を作成
王様に話す受注
案山子を倒す
王様に話して次のイベント

**Comment by darkstars-hub** [comment]
カメラコントローラのばねはいらないカメラのアングル調整
パーティクルエフェクトをにする

**Comment by darkstars-hub** [comment]
フェンスの位置変える

**Comment by darkstars-hub** [comment]
カメラ切替タイミングが不自然
