### ISSUE TITLE
Enemyクラスについて

### ISSUE THREAD

**Issue by darkstars-hub** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#29]

**Comment by darkstars-hub** [comment]
敵キャラが死んだときに ゲーム空間から消すのはどのタイミングが妥当か？

**Comment by KoreanGinseng** [comment]
ラチェットだと、敵の数が変わらないと思うから、固定長でActiveか非Activeかでいいのでは？

**Comment by darkstars-hub** [comment]
GameWorldに実体を持たせて Rendererなどではそのポインタを参照する？

**Comment by darkstars-hub** [comment]
GameWorldの開始時に必要な分だけnewするか

**Comment by darkstars-hub** [comment]
理想的なのは巨大なメモリ(Enemy256体分くらい)を確保しておいて
そこにplacement new する

**Comment by KoreanGinseng** [comment]
分裂したり、敵とかオブジェクトから敵がわいてくることがあるのか。
その場合考えると可変長である必要がありそう？もしくは言っている通りに固定長で多めに確保しておく？

**Comment by darkstars-hub** [comment]
まずは作りやすいポインタの配列で作っておいて
速度が落ちるなら変更する方向でいく

**Comment by darkstars-hub** [comment]
移動する機能をビヘイビアツリーを制御させる

**Comment by darkstars-hub** [comment]
ビヘイビア実行クラスを作成するクラスを作成
ルートノードをデータを外部ファイルに書き出した

**Comment by darkstars-hub** [comment]
現在の表示中のキャラクターにアニメーションをつけたいので
モーションクラスのラッパーを作成する

**Comment by darkstars-hub** [comment]
Enemyの思考状態を定義して状態ごとに行動を変えさせるために
AIStateクラスを作成し各Stateにビヘイビアの実行クラスを持たせる

**Comment by darkstars-hub** [comment]
状態クラスを定義したので
Enemyの攻撃状態移動状態のクラスを作成する
ベースクラスのCharacterも使えるつくりにする検討する
