### ISSUE TITLE
ステージデータの保存形式、拡張子、データ順について

### ISSUE THREAD

**Issue by KoreanGinseng** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#4]
エディタで出力するファイルをどうするかについて。
保存形式決めて、拡張子はどうでもいいけど、データの並びとか何を保存したらいいかとか。
追加でほしいデータとか。

**Comment by OIC-Shinchaemin** [comment]
やはりJSON?

**Comment by KoreanGinseng** [comment]
jsonであればc++で使えるのが
https://cppmap.github.io/libraries/text-data/
ここに列挙されてます。どれ使う？

**Comment by darkstars-hub** [comment]
jsonでいいと思います
個人的にはRapidJSONがおすすめです

**Comment by KoreanGinseng** [comment]
RapidJSONがすでに入れてあるみたいなのでそれを使うようにします。
