### ISSUE TITLE
岡田さんの企画あつめ

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#53]
アイデア草案一覧
例：０．○○○○○○○○○○○○
　　→どう楽しんでもらうか書いてある。
　　概要：リンク先にワードもしくはエクセルの資料があり、もう少しイメージしやすい物になっている。

1.犬が街を壊したり人間に攻撃したりできる緩い雰囲気のゲーム(発表していた犬の物)
→破壊したり吹きとばした時の爽快感を楽しんでもらう。

2．ステージには針や嫌な攻撃をしてくる敵などストレスしか溜まらないゲームだがクリアした時の快感を楽しんでもらう2Dアクションゲーム。(発表していたスライムの物)
 → ストレスしか溜まらないゲームだがクリアした時の快感を楽しんでもらう
概要：https://drive.google.com/file/d/1peju4UoqzDJ0Bi9qt-qh3LNAv1Z8Fyz7/view?usp=sharing
ステージ概要：https://drive.google.com/file/d/1QR_0enTZMkkbXd-rqbdIt5JL7wgwtD79/view?usp=sharing
敵キャラクター概要：https://drive.google.com/file/d/1s3_Qa1RXOuAqOWmFdHPCmRyIS15UHG6p/view?usp=sharing

3．一度動き出すと止まらないキャラクターをゴールに導くパズルゲーム。
→あらかじめ予想していた通りにキャラクターが動かせてゲームをクリアできた時に面白いと感じてもらう

4．プレイヤーの周囲から円型のノーツが飛んできて、当たり判定の部分とうまく重なって押すことができると威力が上がって敵を倒しやすくなるリズムゲームとシューティングゲームを合わせた横スクロールのゲーム
→従来のシューティングゲームに追加要素として攻撃の強化方法としてリズム要素を加えタイミングよく押すことで敵を簡単に倒すことができる爽快感を楽しんでもらう

5．ゲームをスタートすると選択肢が3つあってその中から一つを選んで戦闘するローグライクRPG？選択肢には戦闘、休息、商人などがある、ゲームのスタート前に4人パーティーを組めてジョブを決めたりすることができる条件を達成したり選択肢によって新しいジョブが開放されたりする。
→何度も挑戦して新しく手に入れたキャラを使った編成を考えて、前回の挑戦より先に進んでいく達成感で面白いと思ってもらう

6．索敵能力が発達したグロテスクなミュータントから逃げたり戦ったりするステルスゲーム、敵に近づきすぎて緊張した時の心拍数や走ったりした時の肺活量でバレる。敵に体の一部に弱点があるのでそれを隠れながら見つけて攻撃する。
→バレるかバレないかの緊張感やそれをクリアした時の達成感を楽しんでもらう

7．時間内に鼻毛を抜くゲーム、自動で左右に動く手を鼻毛の位置でタイミングよく押してつかむ、下にフリックすれば鼻毛は抜けるがフリックの速さの判定も渋く早すぎると滑って取れなかったりする。
→制限時間があるのに焦っているとフリックの判定でミスしてしまいイライラが溜まる、そんな極限までイライラしている状態でクリアした時の息の抜ける感じ・爽快感を楽しんでもらう

8．車に銃や盾などをカスタマイズして妨害しながら一位を目指すレースゲーム。銃や盾を付けすぎるとスピードが遅くなったりする。
→油断していると攻撃されて順位が落ちてしまうので油断できない緊張感やカスタマイズで自分が操作しやすい車を見つけたりして楽しんでもらう

9．7日間の授業中に先生からバレずにサボるゲーム。ゲーム内のパソコンの画面を切り替えて動画を見たりゲームをしたりして自分の満足ゲージ授業時間内に貯める。日付が立つごとに先生の人数が増えたり隣の席の奴が先生を呼んだりして邪魔をしてくる。
→先生に見つかってしまうんじゃないかという緊張感を楽しんでもらう

10．背中についたジェットパックのゲージ内に陸から陸へ渡るゲーム。道中に鳥や撃ち落とそうとしてくる敵、針のついている壁などをよけながら進む。
→ステージの状況を見ながらジェットパックのゲージをリアルタイムに判断して節約したりよけたりして考えた末ゴールした時の快感を楽しんでもらう

11．ボールを取り合うゲーム。プレイヤーは特殊な能力のあるキャラクターを一人選びボールを取り合って一番長くボールを持っていた人の勝ち、ボールを持っているプレイヤーを殴ることで落とさせることができる。キャラクターの能力には一定時間透明や移動速度上昇など
→能力の使うタイミングや他のプレイヤーの動きを見て自分の行動を変える読みあいなどの競技性を楽しんでほしい

12．上から物を落として障害物をよけながら箱に入れるゲーム。
→重力加速でだんだんスピードが速くなるので障害物をよけるのに瞬発力が大切になっていく、そこを楽しんでもらう。

13．複雑な構造をしている大阪駅を舞台に鬼ごっこをするゲーム。時間制限までに逃げているプレイヤーが逃げ切れば逃げているプレイヤーの勝ち。逃げてるプレイヤー全員が捕まれば鬼のプレイヤーの勝ち。プレイ人数は20人単位でやってもいいと思う
→複雑なマップで逃げ切ったあるいは捕まえ切った時の勝利への満足感を楽しんでもらう。

14．宇宙将棋
名前の通り宇宙人によって移動できるマスが変わったり攻撃されたときや攻撃するときに効果を発動する駒を勝負前に６つ設定し相手が設定した王をとるもしくは詰ませれば勝ち
→駒や編成によって変わる戦局を楽しんでもらったり動かし方や相手の動きの読み合いを楽しんでほしい。

**Comment by utasaki** [comment]
アレ面白いんじゃない？？？

**Comment by OIC-Shinchaemin** [comment]
そうですねー

**Comment by Clare1224** [comment]
面白そうです。

**Comment by nagishimizu** [comment]
コメントです

**Comment by KoreanGinseng** [comment]
>3．一度動き出すと止まらないキャラクターをゴールに導くパズルゲーム
ランゲーム好きだから面白そうだけど、パズル要素が気になる。

**Comment by KoreanGinseng** [comment]
>4．プレイヤーの周囲から円型のノーツが飛んできて、当たり判定の部分とうまく重なって押すことができると威力が上がって敵を倒しやすくなるリズムゲームとシューティングゲームを合わせたゲーム

ゲーム画面のイメージができない

**Comment by KoreanGinseng** [comment]
>6．索敵能力が発達したグロテスクなミュータントから逃げたり戦ったりするステルスゲーム、敵に近づきすぎて緊張した時の心拍数や走ったりした時の肺活量でバレる。敵に体の一部に弱点があるのでそれを隠れながら見つけて攻撃する。バレるかバレないかの緊張感を楽しんでもらう。

達成報酬が欲しい

**Comment by KoreanGinseng** [comment]
>7．時間内に鼻毛を抜くゲーム、自動で左右に動く手を鼻毛の位置でタイミングよく押してつかむ、下にフリックすれば鼻毛は抜けるがフリックの速さの判定も渋く早すぎると滑って取れなかったりする。

大好き

**Comment by KoreanGinseng** [comment]
>8．車に銃や盾などをカスタマイズして妨害しながら一位を目指すレースゲーム。銃や盾を付けすぎるとスピードが遅くなったりする。
9．7日間の授業中に先生からバレずにサボるゲーム。ゲーム内のパソコンの画面を切り替えて動画を見たりゲームをしたりして自分の満足ゲージ授業時間内に貯める。日付が立つごとに先生の人数が増えたり隣の席の奴が先生を呼んだりして邪魔をしてくる。

面白さが薄い気がする

**Comment by KoreanGinseng** [comment]
>10．背中についたジェットパックのゲージ内に陸から陸へ渡るゲーム。道中に鳥や撃ち落とそうとしてくる敵、針のついている壁などをよけながら進む。

ラチェクラ２のパラグライダー？の妨害ある感じのやつっぽい。いいね。

**Comment by KoreanGinseng** [comment]
>11．ボールを取り合うゲーム。プレイヤーは特殊な能力のあるキャラクターを一人選びボールを取り合って一番長くボールを持っていた人の勝ち、ボールを持っているプレイヤーを殴ることで落とさせることができる。キャラクターの能力には一定時間透明や移動速度上昇など

TeaParty2？

**Comment by KoreanGinseng** [comment]
>12．上から物を落として障害物をよけながら箱に入れるゲーム。

操作難しそう

**Comment by KoreanGinseng** [comment]
>13．複雑な構造をしている大阪駅を舞台に鬼ごっこをするゲーム。

広すぎて難しそう？鬼の数がどれくらいかにもよる？逃走中？

**Comment by darkstars-hub** [comment]
感想

1.犬が街を壊したり人間に攻撃したりできる緩い雰囲気のゲーム(発表していた犬の物)
→ゲーム性とは関係ないけど人間が操作キャラになる（発表で言ってた）よりも他の動物がいいと思う。
ゲームの目的が人間を攻撃することならイノシシだけで事足りるとも思った。
動物の鳴き声がたくさんしたら、にぎやかで楽しそうだと思う。


2．ステージには針や嫌な攻撃をしてくる敵などストレスしか溜まらないゲームだがクリアした時の快感を楽しんでもらう2Dアクションゲーム。(発表していたスライムの物)
→敵がめちゃくちゃ強いならステルスゲームの側面もありそう
「水中に隠れられるけど溶ける」の他に環境（ステージ）に強く関連づいた
リスク有りのアクションがもっと欲しい


3．一度動き出すと止まらないキャラクターをゴールに導くパズルゲーム。
→道を作って任意を道を進ませる？
パズルよりアクションゲームが好き


4．プレイヤーの周囲から円型のノーツが飛んできて、当たり判定の部分とうまく重なって押すことができると威力が上がって敵を倒しやすくなるリズムゲームとシューティングゲームを合わせた横スクロールのゲーム
→シューティングゲームというと敵の弾を避けるのに専念して、発射ボタンはほとんど押しっぱなしのイメージ
そこにもう一つプレイヤーが注意を割かないといけない要素が追加されるのは、
難易度が高くなりそう、画面が雑然としそう
うまく作りこんだら面白そう


5．ゲームをスタートすると選択肢が3つあってその中から一つを選んで戦闘するローグライクRPG？選択肢には戦闘、休息、商人などがある、ゲームのスタート前に4人パーティーを組めてジョブを決めたりすることができる条件を達成したり選択肢によって新しいジョブが開放されたりする。
→よくあるローグライク系だと思う（ダンジョンとかがあるのかな？）
外国のゲームだと死んだキャラは二度と生き返らない（ロストする）と思う


6．索敵能力が発達したグロテスクなミュータントから逃げたり戦ったりするステルスゲーム、敵に近づきすぎて緊張した時の心拍数や走ったりした時の肺活量でバレる。敵に体の一部に弱点があるのでそれを隠れながら見つけて攻撃する。
→オーソドックスなステルスゲーム？


7．時間内に鼻毛を抜くゲーム、自動で左右に動く手を鼻毛の位置でタイミングよく押してつかむ、下にフリックすれば鼻毛は抜けるがフリックの速さの判定も渋く早すぎると滑って取れなかったりする。
→メイドインワリオとかにある10~20秒くらいで遊べるゲームをイメージした。
ボリュームは小さいけどわかりやすいので、
こういったものをたくさん集めて１つのゲームとしてもいいと思う


8．車に銃や盾などをカスタマイズして妨害しながら一位を目指すレースゲーム。銃や盾を付けすぎるとスピードが遅くなったりする。
→カスタマイズのタイミングがレース前なのか、レース中なのかは気になるところ。
プレイヤー妨害するとき、その相手はプレイヤーより順位は上のはず、
妨害する自分は銃を持っている＝銃をつけて遅くなる
妨害したい相手は持っていない＝持っていないから速い
妨害したくても有効範囲外に逃げられて難しいように思えた。
個人的に動かしながらのカスタマイズできる要素はすごくいいと思う


9．7日間の授業中に先生からバレずにサボるゲーム。ゲーム内のパソコンの画面を切り替えて動画を見たりゲームをしたりして自分の満足ゲージ授業時間内に貯める。日付が立つごとに先生の人数が増えたり隣の席の奴が先生を呼んだりして邪魔をしてくる。
→「ゲームをしたり」の部分を「7．時間内に鼻毛を抜くゲーム」とかにしてもいいと思う。


10．背中についたジェットパックのゲージ内に陸から陸へ渡るゲーム。道中に鳥や撃ち落とそうとしてくる敵、針のついている壁などをよけながら進む。
→よけるゲーム？　３Ｄの方がいいと思う


11．ボールを取り合うゲーム。プレイヤーは特殊な能力のあるキャラクターを一人選びボールを取り合って一番長くボールを持っていた人の勝ち、ボールを持っているプレイヤーを殴ることで落とさせることができる。キャラクターの能力には一定時間透明や移動速度上昇など
→最後に持っていた人でなく一番長く持っていた人というのは珍しいと思う。
おそらく制限時間があるだろうけど、遊ぶ人数によっては時間の後半は消化試合になりそう


12．上から物を落として障害物をよけながら箱に入れるゲーム。
→「落として」、「よけながら」ということは
プレイヤーが落とすタイミングと箱どちらも操作できるということ？
いくらか簡単な気がするので、瞬発力がある人でもうっかり失敗してしまう（注意を引いて妨害する）ものが欲しい


13．複雑な構造をしている大阪駅を舞台に鬼ごっこをするゲーム。時間制限までに逃げているプレイヤーが逃げ切れば逃げているプレイヤーの勝ち。逃げてるプレイヤー全員が捕まれば鬼のプレイヤーの勝ち。プレイ人数は20人単位でやってもいいと思う
→追いかけられていない人や捕まってしまった人が退屈しないギミックが欲しい、
既定のメッセージを送れるチャット機能があるといいと思う
シンプルなルールだけに、鬼がどれくらい有利かなどのゲームバランスの調整が難しそう
パーティーゲームとして楽しそうだと思う



個人的には４、８、１３が刺さった。６、１０の雰囲気もいいと思う

**Comment by utasaki** [comment]
1.雰囲気はTOKYO JUNGLEに近いかと思ったのですが復讐方法殺戮なのに緩い雰囲気ゲーム…イメージはつきますがふわふわしてる気がします。

2.アイワナだったり、ダクソだったり、死にゲーを連想しました。単純に難しいだけより、毎回びっくりさせられる死にポイントがあるのは死にゲーの中でも評価が高めなので参考にしていただきたいです。

3.予め攻撃、移動などの行動をセットして敵を倒すってことでしょうか？頭脳系ですが面白いと思います。

4.こういうゲームやりたいです！！直感的にプレイできて、システムも面白いです。成長要素があったりするのもいいかもですね。MUSE DUSHだったりパタポンとかはそれに近いかもですね。

5.これも面白い気がします。ダンジョンメーカーの勇者ver？？

6.難しそうですね。いわゆる逃げゲーですよね。ある程度目的を持たせてあげるといいと思います。よくあるのがびっくり演出が多いのが評価が高いと思います。

7.wwwww

8.モーターストームにさらに武器が乗った感じでしょうか？そのゲームバランスは盾装備するより回避するほうがよさそうですね:)
クラッシュが見どころだと思うのでそのあたりを主張するといいかもしれません。

9.7日は長いてゲーミング(((
FNAFやメイドインワリオのゲーマーあたりが元ネタでしょうか？

10.アクションゲームの中のギミックとしてはありだとおもいます。これ単体はやりたくないです

11.Tea Party!! 2 (笑) ボールを持って逃げるだけのゲームでしょうか？明確なゴールや目的があるといいかもしれません。

12.アクションゲームの中のギミックとしてはありだとおもいます。これ単体はやりたくないです

13.ハンターも操作できる逃走中？駅ダンジョンをテーマにするのは面白そうですね。

主観と偏見要素強めかもしれません。4,5,8,13が好きです。

**Comment by nagishimizu** [comment]
感想

1.犬が街を壊したり人間に攻撃したりできる緩い雰囲気のゲーム(発表していた犬の物)
→緩いというのはゲームとしては暇つぶし程度には丁度いい感じのゲームということ？世界観は緩くなさそう･･･

2.ステージには針や嫌な攻撃をしてくる敵などストレスしか溜まらないゲームだがクリアした時の快感を楽しんでもらう2Dアクションゲーム。(発表していたスライムの物)
→最弱モンスターと死にゲーの相性は良いと思う。

3.一度動き出すと止まらないキャラクターをゴールに導くパズルゲーム。
→レミングスっぽいゲーム？

4.プレイヤーの周囲から円型のノーツが飛んできて、当たり判定の部分とうまく重なって押すことができると威力が上がって敵を倒しやすくなるリズムゲームとシューティングゲームを合わせた横スクロールのゲーム
→リズムに乗りつつ敵の攻撃を避けるのは難しそう。避けに専念するときと攻撃を強化するときを分けると楽しそう。

5.ゲームをスタートすると選択肢が3つあってその中から一つを選んで戦闘するローグライクRPG？選択肢には戦闘、休息、商人などがある、ゲームのスタート前に4人パーティーを組めてジョブを決めたりすることができる条件を達成したり選択肢によって新しいジョブが開放されたりする。
→FFⅤとかみたいにキャラとジョブは別？やりこみ要素が多くなりそう。

6.索敵能力が発達したグロテスクなミュータントから逃げたり戦ったりするステルスゲーム、敵に近づきすぎて緊張した時の心拍数や走ったりした時の肺活量でバレる。敵に体の一部に弱点があるのでそれを隠れながら見つけて攻撃する。
→演出次第で面白くなりそう。

7.時間内に鼻毛を抜くゲーム、自動で左右に動く手を鼻毛の位置でタイミングよく押してつかむ、下にフリックすれば鼻毛は抜けるがフリックの速さの判定も渋く早すぎると滑って取れなかったりする。
→ミニゲーム集の一つとして出せそう。

8.車に銃や盾などをカスタマイズして妨害しながら一位を目指すレースゲーム。銃や盾を付けすぎるとスピードが遅くなったりする。
→PvPなら3か月くらいで同じカスタマイズばかりという初心者には地獄な光景になりそう。

9.7日間の授業中に先生からバレずにサボるゲーム。ゲーム内のパソコンの画面を切り替えて動画を見たりゲームをしたりして自分の満足ゲージ授業時間内に貯める。日付が立つごとに先生の人数が増えたり隣の席の奴が先生を呼んだりして邪魔をしてくる。
→ミニゲーム集の一つとして出せそう。

10.背中についたジェットパックのゲージ内に陸から陸へ渡るゲーム。道中に鳥や撃ち落とそうとしてくる敵、針のついている壁などをよけながら進む。
→ジェットパックがメインのゲームは完全に好みが分かれそう。

11.ボールを取り合うゲーム。プレイヤーは特殊な能力のあるキャラクターを一人選びボールを取り合って一番長くボールを持っていた人の勝ち、ボールを持っているプレイヤーを殴ることで落とさせることができる。キャラクターの能力には一定時間透明や移動速度上昇など
→制限時間があるなら「長く持ってた人が勝ち」は状況次第でゲームバランスがこわれる。マリオカート8のいただきシャインみたいな感じなら良さげ

12.上から物を落として障害物をよけながら箱に入れるゲーム。
→ミニゲーム集の一つとして出せそう。

13.複雑な構造をしている大阪駅を舞台に鬼ごっこをするゲーム。時間制限までに逃げているプレイヤーが逃げ切れば逃げているプレイヤーの勝ち。逃げてるプレイヤー全員が捕まれば鬼のプレイヤーの勝ち。プレイ人数は20人単位でやってもいいと思う
→大阪に住んでない人には伝わらない場合もあるから大阪駅限定にするのではなく、各地方の迷いやすい所も入れてもよさそう。
