### ISSUE TITLE
今までのチケット消化

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#6]
現在、Redmineにあるチケットの消化お願いします。
方法としては、

軽く作業内容を書いて、ステータスを「完了」に変更

で構いません。

全く作業してないタスクも、「チームプロジェクト開始により消化」って書いてください。

終わったら、こちらに返事の形で残しておいてください。

**Comment by darkstars-hub** [comment]
3/9時点で作成された作業を４つのステータスを完了にしました

**Comment by KoreanGinseng** [comment]
ここを見ないで完了にしてしまったのでメッセージ違うこと書いてますが、前の４つ完了にしました。

**Comment by yuto10** [comment]
完了にしました
