### ISSUE TITLE
.ignoreの場所移動（Mof）

### ISSUE THREAD

**Issue by KoreanGinseng** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#62]

**Comment by OIC-Shinchaemin** [comment]
そのあとにUnityブランチにUnity用GitIgnore作成
→　shin予定

**Comment by OIC-Shinchaemin** [comment]
Unity用GitIgnoreアップしました。
https://github.com/OIC-Shinchaemin/RatchetNclank-PrivateCopy/commit/e568704b4fad3f753c641c2aa6c53fa53a595054
