### ISSUE TITLE
ステージエディターのレビュー

### ISSUE THREAD

**Issue by yuto10** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#74]

**Comment by utasaki** [comment]
・強制設置モードいらないかも
・ウィンドウサイズを変更、もしくはフルスクリーン表示できるようにしてほしい
・ドラッグは一番右までカーソルが移動したら左に行けるようになってほしい
・オブジェクトのコピーが欲しい
・rotationの指定をラジアンではなくデブリ角で指定できるようにしてほしい
・操作の保存のタイミングを変えてほしい(ドラッグを使うときに不便なタイミング)
