### ISSUE TITLE
ゲーム改善すべきところ

### ISSUE THREAD

**Issue by nagishimizu** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#76]

**Comment by nagishimizu** [comment]
死亡時･･･ていうかステージ開始前に中間のシーンみたいな奴を実装する

**Comment by nagishimizu** [comment]
ゲームとしての面白さを突き詰める

**Comment by utasaki** [comment]
ボスの強さで面白さ調整しようと思ってるんだけど、正直自分がプレイするゲームで好きなのって成長要素なんだよね()

**Comment by utasaki** [comment]
ボスの種類を増やすためにステージの拡張は必須です〇

**Comment by nagishimizu** [comment]
死亡時の明確なデメリットが欲しいから残機システムとか実装したい
