### ISSUE TITLE
MofLibraryの修正について

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#8]
川村さん、書いてください。

**Comment by darkstars-hub** [comment]
メンバー宣言では修飾名は使用できません
このエラーが出たのでライブラリ内のヘッダの一部を書き換えました

**Comment by OIC-Shinchaemin** [comment]
それをGitに上げましょうか

**Comment by darkstars-hub** [comment]
チケットを作成しました
https://ex-oic.cloudmine.jp/issues/31

**Comment by darkstars-hub** [comment]
https://ex-oic.cloudmine.jp/issues/34
のついでに「MofLibrary2017.lib」「MofLibrary2017_d.lib」をリンクでもらった新しいものに入れ替えました

デバッグビルドでしか試してませんが
新しい方のライブラリをリンクして実行した場合
CFontクラスのRenderString関数でエラーが出ました
解決はまだできていません
