### ISSUE TITLE
GitIgnoreのアップデート

### ISSUE THREAD

**Issue by OIC-Shinchaemin** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#9]

**Comment by OIC-Shinchaemin** [comment]
井上さんお願いします。

**Comment by KoreanGinseng** [comment]
ignoreみましたけど、僕の持ってるやつ入れると.lib消してしまうし、vs2015用のなので今のままで大丈夫だと思います。
.gitattributesだけ入れときます。

**Comment by OIC-Shinchaemin** [comment]
MofLibブランチに入れてほしいので、PullRequest形式でお願いします。

**Comment by KoreanGinseng** [comment]
もうcommitとpushしてしまっているのですが、一度消してbranch作ってPullRequestしたほうがいいですか？
