### ISSUE TITLE
最低限のゲームループについて

### ISSUE THREAD

**Issue by darkstars-hub** [OIC-Shinchaemin/RatchetNclank-PrivateCopy#96]

**Comment by darkstars-hub** [comment]
タイトルとゲームのシーン作成

**Comment by darkstars-hub** [comment]
コピー元の敵の配置を真似る

**Comment by darkstars-hub** [comment]
Hp回復・弾薬回復・ボルトが入っている箱

**Comment by darkstars-hub** [comment]
デバッグ表示の処理を整理する
不要なものは消す

**Comment by darkstars-hub** [comment]
ステージのギミックの形状などは実際のステージに合わせる

**Comment by darkstars-hub** [comment]
敵の動きは最低限２種類近距離攻撃と遠距離を作る、できるなら近距離タイプの移動を少しバリエーションを加える

**Comment by darkstars-hub** [comment]
最低限のステージ作りは
少なくとも二つで
１つはチュートリアルステージで
２つめが遊んでほしいステージ

場面転換でいうと

**Comment by darkstars-hub** [comment]
ゲームの進行具合がわかるようにする

そっちに向かいたくなるような作りにする

**Comment by darkstars-hub** [comment]
床と空をて

敵の色をシェーダとかで変える　わりりやすくする　大きさ変えたりもする

**Comment by darkstars-hub** [comment]
突然の場面転換しない

フェードインしたい

**Comment by KoreanGinseng** [comment]
ステージ自体が完コピにするわけではないので配置をまねるのは厳しいかと思う
一直線やL字だけのチュートリアルでもばらけさせることができるだろうしそれでいいと思う
